project_name: acr-tag
before:
  hooks:
    - go mod download
builds:
  - main: .
    binary: acr-tag
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X "tag.app_version={{.Version}}"
      - -s -w -X "tag.commit={{.ShortCommit}}"
      - -s -w -X "tag.date={{.CommitDate}}"
      - -s -w -X "tag.builtBy=goreleaser"
archives:
  - format_overrides:
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
